- name: Create Persistent Volume and Persistent Volume Claim for MySQL
  hosts: target_machine
  tasks:
    - name: Create Persistent Volume
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: mysql-pv
            namespace: "{{ namespace }}"
          spec:
            capacity:
              storage: 1Gi
            accessModes:
              - ReadWriteOnce
            hostPath:
              path: /data/mysql_data
            storageClassName: manual

    - name: Create Persistent Volume Claim
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: mysql-pvc
            namespace: "{{ namespace }}"
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
            storageClassName: manual