- name: Deploy MySQL with Persistent Volume Claim
  hosts: target_machine
  tasks:
    - name: Create MySQL Deployment
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mysql-deployment
            namespace: "{{ namespace }}"
          spec:
            replicas: "{{ replicas }}"
            selector:
              matchLabels:
                app: "{{ mysql_label }}"
            template:
              metadata:
                labels:
                  app: "{{ mysql_label }}"
              spec:
                containers:
                - name: mysql
                  image: mysql:latest
                  env:
                    - name: ALLOW_EMPTY_PASSWORD
                      value: "yes"
                    - name: MYSQL_ROOT_PASSWORD
                      value: "rootpwd"
                    - name: MYSQL_DATABASE
                      value: "appdata"
                    - name: MYSQL_USER
                      value: "user"
                    - name: MYSQL_PASSWORD
                      value: "userpwd"
                  ports:
                  - containerPort: 3306
                  volumeMounts:
                  - name: mysql-storage
                    mountPath: /var/lib/mysql
                volumes:
                - name: mysql-storage
                  persistentVolumeClaim:
                    claimName: mysql-pvc

    - name: Create MySQL Service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mysql-service
            namespace: "{{ namespace }}"
          spec:
            selector:
              app: "{{ mysql_label }}"
            ports:
            - protocol: TCP
              port: 3306
              targetPort: 3306
            type: ClusterIP