---
- name: Install Docker and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
      when: ansible_os_family == "Debian"

    - name: Check if Docker is installed
      command: docker --version
      register: docker_version
      ignore_errors: yes

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      when: docker_version.failed

    - name: Add Docker GPG key
      apt_key:
        url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
        state: present
      when: docker_version.failed

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu focal stable
        state: present
      when: docker_version.failed

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: docker_version.failed

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: docker_version.failed

    - name: Configure Docker to use Aliyun registry mirror
      lineinfile:
        path: /etc/docker/daemon.json
        line: '{"registry-mirrors": ["https://docker.mirrors.ustc.edu.cn"]}'
        create: yes
      notify:
        - Restart Docker
      when: docker_version.failed

  handlers:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
      when: docker_version.failed