---
- name: Install K3s using China mirror
  hosts: all
  become: yes
  tasks:
    - name: Download and install K3s using Rancher China mirror
      shell: |
        curl -sfL https://rancher-mirror.rancher.cn/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn sh -
      args:
        executable: /bin/bash

    - name: Ensure K3s service is running
      systemd:
        name: k3s
        state: started
        enabled: yes

    - name: Verify K3s installation
      command: kubectl get nodes
      register: k3s_nodes
      changed_when: false

    - name: Show K3s nodes
      debug:
        msg: "{{ k3s_nodes.stdout }}"