---
- name: Set up kubeconfig for K3s cluster
  hosts: target_machine
  become: true
  tasks:

    - name: Ensure .kube directory exists
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy file from source to destination
      ansible.builtin.command:
        cmd: cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

    - name: Verify kubectl can connect to the cluster
      ansible.builtin.shell: "kubectl get nodes"
      register: kubectl_output
      failed_when: "'No resources found' in kubectl_output.stdout"

    - name: Debug output from kubectl
      ansible.builtin.debug:
        var: kubectl_output.stdout